In [35]:
from sklearn.datasets import load_boston

In [36]:
boston = load_boston()
X = boston.data # input
Y = boston.target

In [37]:
X.shape

(506, 13)

In [38]:
Y.shape

(506,)

In [39]:
#sklearn.datasets.load_diabetes(*, return_X_y=False, as_frame=False)

In [40]:
from sklearn.datasets import load_diabetes

In [41]:
diabetes = load_diabetes()
X = diabetes.data
Y = diabetes.target

In [42]:
X.shape

(442, 10)

In [43]:
Y.shape

(442,)

In [44]:
#we have 506 samples with 13 features and a single target value

# scikit-learn also provides functions for creating
dummy datasets from scratch: make_classification(), make_regression(), and make_blobs() (particularly useful for testing cluster algorithms). They're very easy to use and in many cases, it's the best choice to test a model without loading more complex datasets.

In [45]:
#https://scikit-learn.org/stable/datasets/toy_dataset.html

In [46]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=1000)

In [47]:
from sklearn.utils import check_random_state
rs = check_random_state(1000)

In [48]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y,
test_size=0.25, random_state=rs)

In [49]:
import numpy as np
X = np.random.uniform(0.0, 1.0, size=(10, 2))
Y = np.random.choice(('Male','Female'), size=(10))
#Y = np.random.choice(('Small','Large'), size=(10))

In [50]:
X

array([[0.60695146, 0.62360797],
       [0.51617695, 0.24246621],
       [0.88283305, 0.22390766],
       [0.97557126, 0.85623521],
       [0.69104448, 0.52150097],
       [0.89480502, 0.96421641],
       [0.57967042, 0.75125578],
       [0.44803687, 0.8251649 ],
       [0.70618725, 0.10271909],
       [0.68716062, 0.06567408]])

In [51]:
X[0]

array([0.60695146, 0.62360797])

In [52]:
Y

array(['Male', 'Male', 'Male', 'Female', 'Female', 'Male', 'Male',
       'Female', 'Male', 'Female'], dtype='<U6')

In [53]:
Y[0]

'Male'

In [54]:
Y

array(['Male', 'Male', 'Male', 'Female', 'Female', 'Male', 'Male',
       'Female', 'Male', 'Female'], dtype='<U6')

In [55]:
Y[1]

'Male'

In [56]:
Y[0]

'Male'

In [57]:
Y[1]

'Male'

In [58]:
X


array([[0.60695146, 0.62360797],
       [0.51617695, 0.24246621],
       [0.88283305, 0.22390766],
       [0.97557126, 0.85623521],
       [0.69104448, 0.52150097],
       [0.89480502, 0.96421641],
       [0.57967042, 0.75125578],
       [0.44803687, 0.8251649 ],
       [0.70618725, 0.10271909],
       [0.68716062, 0.06567408]])

In [59]:
Y

array(['Male', 'Male', 'Male', 'Female', 'Female', 'Male', 'Male',
       'Female', 'Male', 'Female'], dtype='<U6')

In [60]:
Y[5]

'Male'

In [61]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
yt = le.fit_transform(Y)
print(yt)

[1 1 1 0 0 1 1 0 1 0]


In [62]:
output = [1, 0, 1, 1, 0, 0]

In [63]:
decoded_output = [le.classes_[i] for i in output]

In [64]:
decoded_output

['Male', 'Female', 'Male', 'Male', 'Female', 'Female']

In [65]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
Yb = lb.fit_transform(Y)

In [66]:
Yb

array([[1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0]])

In [67]:
Y

array(['Male', 'Male', 'Male', 'Female', 'Female', 'Male', 'Male',
       'Female', 'Male', 'Female'], dtype='<U6')

In [68]:
lb.inverse_transform(Yb)

array(['Male', 'Male', 'Male', 'Female', 'Female', 'Male', 'Male',
       'Female', 'Male', 'Female'], dtype='<U6')

In [69]:
#Y = lb.fit_transform(Y)

#Yp = model.predict(X[0])

#Ypr = np.round(Yp)

#lb.inverse_transform(Ypr)


In [70]:
from sklearn.preprocessing import Imputer
import numpy as np

In [71]:
data = np.array([[1, np.nan, 2], [2, 3, np.nan], [-1, 4, 2]])

In [7]:
imp = Imputer(strategy='mean')
imp.fit_transform(data)

array([[ 1. ,  3.5,  2. ],
       [ 2. ,  3. ,  2. ],
       [-1. ,  4. ,  2. ]])